# slack home-stack-dns2
version: "3"

services:

  pihole2:
    image: pihole/pihole:latest
    container_name: pihole2
    hostname: 'pi.hole'
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: '${timezone}'
      TEMPERATUREUNIT: 'c'
      WEBPASSWORD: '${pihole_password}'
      QUERY_LOGGING: 'true'
    volumes:
      - 'pihole:/etc/pihole'
      - 'dnsmasq.d:/etc/dnsmasq.d'
    networks:
      net_frontend:
        ipv4_address: ${dns2_ip}


volumes:

  pihole:
    driver: local

  dnsmasq.d:
    driver: local


networks:

  net_frontend:
    name: home_frontend
    external: true