# Pi Hole Stack - rpi5
version: "3.3"

services:

  pihole5:
    image: pihole/pihole:latest
    container_name: pihole5
    hostname: 'pi.hole5'
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: '${timezone}'
      TEMPERATUREUNIT: 'c'
      WEBPASSWORD: '${pihole_password}'
      DNSMASQ_LISTENING: 'all'
      QUERY_LOGGING: 'true'
    volumes:
      - 'pihole:/etc/pihole'
      - 'dnsmasq.d:/etc/dnsmasq.d'    


volumes:
  pihole:
    driver: local

  dnsmasq.d:
    driver: local
