# slack home-stack
version: "3"

services:

  torrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - TZ='${timezone}'
      - WEBUI_PORT=8080
    volumes:
      - torrent_config:/config
      - torrent_download:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
    labels:
      #- "traefik.enable=true"
      #- "traefik.http.routers.torrent.rule=Host(`torrent.${domain_name}`)"
      #- "traefik.http.routers.torrent.tls.certresolver=le"
      #- "traefik.http.routers.torrent.entrypoints=websecure"
      #- "traefik.http.services.torrent.loadbalancer.server.port=8080"
    networks:
      net_backend_shared:


volumes:

  torrent_config:
    driver: local

  torrent_download:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${data}/torrent'



networks:

  net_backend_shared:
      name: home_backend_shared
